<?xml version="1.0"?>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output encoding="iso-8859-1"/><!--Or change to utf8-->
<xsl:output method="text" />

<xsl:template match="rudeWordList">anus arse arsehole arsewipe arsing ass assbag assbandit assbanger assbite assclown asscock asscracker asses assface assfuck assfucker assgoblin asshat asshead asshole asshopper assjacker asslick asslicker assmunch assmuncher asspirate assshole asswipe ballbagsbampot bastard beaner bitch bitchass bitchtits bitchy bloody blowjob bollock bollocked bollocking bollocks bollox boner brotherfucker bugger buggering buggered bullshit bumblefuck butt butt-pirate buttfucka buttfucker carpetmuncher chinc chink choad chode christ clit clitface clitfuck cock cockbite cockface cockfucker cockknoker cockmaster cockmongler cockmongruel cockmonkey cockmuncher cocknugget cockshit cocksmith cocksmoker cocksucker coochie coochy coon cooter crap crapper crapping crapped cum cumbubble cumbucket cumjockey cumtart cunnilingus cunt cunthole cunting damn deggo dick dickbag dickbeaters dickface dickfuck dickhead dickhole dickmonger dicks dickweasel dickweed dickwod dicking dicker dildo dipshit dookie douche douche-fag douchebag douchewaffle dumass dumbass dumbfuck dumbshit dumshit dyke fag fagbag fagfucker faggit faggot fagtard fatass fellatio feltch flamer fuck fuckass fuckbrain fuckbutt fucked fucker fuckless fuckface fuckhead fuckhole fuckin fucking fucknut fucks fuckstick fucktard fuckup fuckwad fuckwit fuckwitt fuckwad fudgepacker gay gaybob gaydo gayfuck gayfuckist gaytard gaywad goddamn goddamnit golliwog gooch gook gringo guido handjob heeb hell ho homo homodumbshit honkey humping jackass jap jerk jigaboo jizz junglebunny jesuskike kooch kootch kyke lesbian lesbo lezzie mcfagget minge mothafucka motherfucker motherfucking muff muffdiver munging negro nigga nigger niglet nutsack paki panooch pecker peckerhead penis penisfucker piss pissed pisser pissing pissflaps pollock poon poonani poonany porchmonkey prick punanny punta pussies pussy pussylicking puto queef queer queerbait queerhole renob rimjob ruski sand nigger sandnigger schlong scrote shag shagging shagger shit shitbagger shitcunt shitdick shitface shitfaced shithead shithole shithouse shitspitter shitstain shiter shitted shitless shitting shitter shittiest shitting shitty shiz shiznit sod sodding sodded skank skeet skullfuck slag slagged slagging slut slutbag snatch spastic spic spick sploogeback tard testicle thundercunt tit titfuck tits tittyfuck twat twatlips twats twatwaffle vag vagina vjayjay wank wanker wanking wanked wetback whore whoring whorebag whoreface wop</xsl:template>


</xsl:stylesheet>